In [3]:
import numpy as np

In [8]:
a1 = np.array([1,2,3,4,5])
print([1,2,3,4,5])
print(a1)
print(type(a1))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [145]:
# 변수 a3, 100 아래 3의 배수 
a3 = np.arange(3,100,3)
print(a3)

# 1에서 부터 10 아래 0.5씩 증가하는 숫자, step이 0.5
a4 = np.arange(1.3,10,0.5)
print(a4)

#lista = [i for i in range(1.3, 10, 0.5)]

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [78]:
a4 = np.linspace(0, 10, 15) # stop도 포함.
print(a4)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [85]:
a5 = np.zeros(5)
print(a5)

a6 = np.ones(5, dtype=np.int64)
print(a6)
a6.astype(np.float64)

[0. 0. 0. 0. 0.]
[1 1 1 1 1]


array([1., 1., 1., 1., 1.])

In [92]:
lista = [1,2,3.5,4.2]
a7 = np.array(lista)
print(a7)

listb = [1,2,'abc', 'def']
a8 = np.array(listb)
print(a8)
#a8.astype(np.int64)

[1.  2.  3.5 4.2]
['1' '2' 'abc' 'def']


In [101]:
print(a7.dtype)
print(a7.ndim)
print(a7.shape)
print(a7.size)

print(a7.itemsize)
print(a7.data)

float64
1
(4,)
4
8


In [117]:
a10 = np.arange(10,100,5)
print(a10)
# 특정인덱스
a10[5]
# 스타트, 스탑
print(a10[3:7])
# 스타트, 스탑, 스텝
a10[2:9:2]

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[25 30 35 40]


array([20, 30, 40, 50])

In [119]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[[1,3,7]])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 45]


In [126]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[a10%10==5])

x = (a10%10==5) 
print(x)
print(x.shape)
print(a10.shape)
print(a10[x])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
(18,)
(18,)
[15 25 35 45 55 65 75 85 95]


In [138]:
lista = [x for x in range(5)]
listb = [x for x in range(10,15)]
print(lista)
print(listb)
print(lista + listb)
print(lista - listb)

[0, 1, 2, 3, 4]
[10, 11, 12, 13, 14]
[0, 1, 2, 3, 4, 10, 11, 12, 13, 14]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [141]:
a1 = np.arange(5)
a2 = np.arange(10,15)
print(a1)
print(a2)
print('add:',a1 + a2)
print(   np.concatenate((a1,a2))   )
print('sub:',a1-a2)
print('mul:',a1*a2)
print('div:',a1/a2)

[0 1 2 3 4]
[10 11 12 13 14]
add: [10 12 14 16 18]
[ 0  1  2  3  4 10 11 12 13 14]
sub: [-10 -10 -10 -10 -10]
mul: [ 0 11 24 39 56]
div: [0.         0.09090909 0.16666667 0.23076923 0.28571429]
