In [29]:
import requests
import numpy as np

x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [36]:
raw_data=[]
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
    
for sample in raw_data:
    if len(sample) < 1:
        continue
    for i, value in enumerate(sample[:4]):
        try:
            sample[i] = float(value)
        except:
            sample[i] = 0.0

In [9]:
print(raw_data[:3])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa']]


In [12]:
for e in raw_data:
    try:
        if e[4]=='Iris-setosa':
            e[4]=0
        elif e[4]=='Iris Versicolour':
            e[4]=1
        else:
            e[4]=2
    except:
        pass
print(raw_data[:3])        

[[5.1, 3.5, 1.4, 0.2, 2], [4.9, 3.0, 1.4, 0.2, 2], [4.7, 3.2, 1.3, 0.2, 2]]


In [37]:
for sample in raw_data:
    if len(sample)<2:
        continue
    if 'setosa' in sample[-1]:
        sample[-1]=0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1] = 2.0

In [40]:
print(raw_data[0])
print(raw_data[51])
print(raw_data[101])

[5.1, 3.5, 1.4, 0.2, 0.0]
[6.4, 3.2, 4.5, 1.5, 1.0]
[5.8, 2.7, 5.1, 1.9, 2.0]


In [44]:
print(raw_data[-3:])
print(len(raw_data))
raw_data = raw_data[:150]
print(raw_data[-3:])

[[6.5, 3.0, 5.2, 2.0, 2.0], [6.2, 3.4, 5.4, 2.3, 2.0], [5.9, 3.0, 5.1, 1.8, 2.0]]
150
[[6.5, 3.0, 5.2, 2.0, 2.0], [6.2, 3.4, 5.4, 2.3, 2.0], [5.9, 3.0, 5.1, 1.8, 2.0]]


In [47]:
np_data = np.array(raw_data)
np_data.shape
np_data[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

### 기본 통계값
* 전체 평균, 표준편차 
* 품종별 평균, 표준편차 

* 평균 np.mean()
* 표준편차 np.std()

In [60]:
np_data_mean = np.mean(np_data, axis=0)
print('전체평균',np_data_mean)
np_data_std = np.std(np_data, axis=0)
print('전체 표준편차',np_data_std)

np_data_mean_setosa = np.mean(np_data[:51], axis=0)
print('세토사 평균',np_data_mean_setosa)
np_data_mean_versicolor = np.mean(np_data[51:101], axis=0)
print('베르시컬러 평균', np_data_mean_versicolor)
np_data_mean_virginica= np.mean(np_data[101:], axis=0)
print('비르지니카 평균', np_data_mean_virginica)

np_data_std_setosa = np.std(np_data[:51], axis=0)
print('세토사 표준편차',np_data_std_setosa)
np_data_std_setosa = np.std(np_data[51:101], axis=0)
print('베르시컬러 표준편차',np_data_std_setosa)
np_data_std_setosa = np.std(np_data[101:], axis=0)
print('비르지니카 표준편차',np_data_std_setosa)

전체평균 [5.84333333 3.054      3.75866667 1.19866667 1.        ]
전체 표준편차 [0.82530129 0.43214658 1.75852918 0.76061262 0.81649658]
세토사 평균 [5.04509804 3.41372549 1.52745098 0.26666667 0.01960784]
베르시컬러 평균 [5.922 2.772 4.286 1.348 1.02 ]
비르지니카 평균 [6.59387755 2.96734694 5.54285714 2.01632653 2.        ]
세토사 표준편차 [0.44250345 0.37469967 0.47981959 0.19165601 0.13864839]
베르시컬러 표준편차 [0.49083195 0.31371324 0.52192337 0.25553082 0.14      ]
비르지니카 표준편차 [0.63451996 0.31904689 0.54809503 0.26599596 0.        ]


In [67]:
print(np_data[:3])
print(np.mean(np_data, axis=0))
print(np.std(np_data, axis=0))
print(np.corrcoef(np_data.T)) # 상관도 

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]]
[5.84333333 3.054      3.75866667 1.19866667 1.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.81649658]
[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [71]:
filter_setosa = np_data[:,-1]==0.0
filter_versicolor = np_data[:,-1]==1.0
filter_virginica = np_data[:,-1]==2.0

print(np.mean(np_data[filter_setosa], axis=0))
print(np.std(np_data[filter_setosa], axis=0))

[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
